name: Linter

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/setup-linter #remove me


permissions:
  pull-requests: write
  contents: write

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Linter Check
        run: ./gradlew ktlintCheck

      - uses: minjunkweon/action-ktlint-auto-review@v1
        if: github.event_name == 'pull_request' && always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
