name: Linter

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/setup-linter #remove me


permissions:
  pull-requests: write
  contents: write

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Linter Check
        run: ./gradlew ktlintCheck

      - name: Extract Linter Summary
        id: linter-summary
        run: |
          mkdir -p temp
          if [ -f build/reports/ktlint/ktlint.html ]; then
            # Extract error count summary (you can improve this extraction)
            grep -o 'class="problem[^"]*"' build/reports/ktlint/ktlint.html | wc -l > temp/summary.txt
            echo "summary=$(cat temp/summary.txt)" >> $GITHUB_OUTPUT
          else
            echo "summary=No linter issues found or report not generated." >> $GITHUB_OUTPUT
          fi


      - name: Comment on PR with Linter Summary
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          SUMMARY="${{ steps.linter-summary.outputs.summary }}"
          gh pr comment "$PR_URL" --body "### 🧹 Linter Report Summary\n$SUMMARY issue(s) found. Full HTML report is available as an artifact."
        
