name: Linter

on:
  pull_request:
    branches:
      - main
      - develop


permissions:
  pull-requests: write
  contents: write

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Linter Check
        run: ./gradlew ktlintCheck

      - name: Comment on PR if linter issues found
        if: failure() && github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.html_url }}" --body $'⚠️ **Linter issues detected.**\n\nPlease run `./gradlew ktlintCheck` locally to fix them before merging.'
