name: Linter

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/setup-linter #remove me
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Linter Check
        run: ./gradlew ktlintCheck

      - uses: le0nidas/ktlint-pr-comments@v1.1
        with:
          repotoken: ${{ secrets.GITHUB_TOKEN }}
          arguments: "--disabled_rules=parameter-list-wrapping,final-newline"

